import {
  Buildings,
  Palette,
  Storefront,
  Compass,
  Robot,
  Globe,
  Lightning,
  Key,
  Lock,
  ChartBar,
  DotsThree,
} from '@phosphor-icons/react'
import type { SearchMeta } from '@/lib/dashboard-search/types'

export const searchMetas: SearchMeta[] = [
  {
    id: 'dash.org.general',
    titleKey: 'dashboard.organization.settings.tabs.general',
    descriptionKey: 'dashboard.search.entries.org_general.description',
    keywordsKey: 'dashboard.search.entries.org_general.keywords',
    icon: Buildings,
    href: '/dash/org/settings/general',
    group: 'settings',
    aiSummary: 'Organization general settings: name, slug, description and feature toggles.',
    aiHints: [
      'How do I change the organization name?',
      'How do I enable or disable a feature?',
      'How do I change the slug?',
    ],
  },
  {
    id: 'dash.org.branding',
    titleKey: 'dashboard.organization.settings.tabs.branding',
    descriptionKey: 'dashboard.search.entries.org_branding.description',
    keywordsKey: 'dashboard.search.entries.org_branding.keywords',
    icon: Palette,
    href: '/dash/org/settings/branding',
    group: 'settings',
    aiSummary: 'Branding: logo, favicon, colours and font applied across the organization site.',
    aiHints: [
      'How do I change the logo?',
      'How do I set the brand colour?',
      'How do I change the font?',
      'How do I remove the ValidBridge badge?',
    ],
  },
  {
    id: 'dash.org.landing',
    titleKey: 'dashboard.organization.settings.tabs.landing',
    descriptionKey: 'dashboard.search.entries.org_landing.description',
    keywordsKey: 'dashboard.search.entries.org_landing.keywords',
    icon: Storefront,
    href: '/dash/org/settings/landing',
    group: 'settings',
    aiSummary: 'Landing page: a custom homepage for the organization, replacing the course catalogue.',
    aiHints: [
      'How do I build a landing page?',
      'How do I add sections and calls to action?',
      'How do I publish the landing page?',
    ],
  },
  {
    id: 'dash.org.seo',
    titleKey: 'dashboard.organization.settings.tabs.seo',
    descriptionKey: 'dashboard.search.entries.org_seo.description',
    keywordsKey: 'dashboard.search.entries.org_seo.keywords',
    icon: Compass,
    href: '/dash/org/settings/seo',
    group: 'settings',
    aiSummary: 'SEO: meta titles, descriptions, social images and sitemap for the organization site.',
    aiHints: [
      'How do I set the meta title?',
      'How do I add a social share image?',
      'How do I manage the sitemap?',
    ],
  },
  {
    id: 'dash.org.ai',
    titleKey: 'dashboard.organization.settings.tabs.ai',
    descriptionKey: 'dashboard.search.entries.org_ai.description',
    keywordsKey: 'dashboard.search.entries.org_ai.keywords',
    icon: Robot,
    href: '/dash/org/settings/ai',
    group: 'settings',
    aiSummary: 'AI settings: enable AI, cap requests per user and toggle AI surfaces.',
    aiHints: [
      'How do I turn AI on or off?',
      'How do I set a per-user request limit?',
      'How do I buy more AI credits?',
    ],
  },
  {
    id: 'dash.org.domains',
    titleKey: 'dashboard.organization.settings.tabs.domains',
    descriptionKey: 'dashboard.search.entries.org_domains.description',
    keywordsKey: 'dashboard.search.entries.org_domains.keywords',
    icon: Globe,
    href: '/dash/org/settings/domains',
    group: 'settings',
    aiSummary: 'Custom domains: connect your own domain and manage SSL.',
    aiHints: [
      'How do I connect a custom domain?',
      'How do I set up SSL?',
      'How do I use a subdomain?',
    ],
  },
  {
    id: 'dash.org.automations',
    titleKey: 'dashboard.organization.settings.tabs.automations',
    descriptionKey: 'dashboard.search.entries.org_automations.description',
    keywordsKey: 'dashboard.search.entries.org_automations.keywords',
    icon: Lightning,
    href: '/dash/org/settings/automations',
    group: 'settings',
    aiSummary: 'Automations: webhooks, scheduled actions and integrations.',
    aiHints: [
      'How do I create a webhook?',
      'How do I connect Zapier?',
      'How do I set up an automation?',
    ],
  },
  {
    id: 'dash.org.api',
    titleKey: 'dashboard.organization.settings.tabs.api',
    descriptionKey: 'dashboard.search.entries.org_api.description',
    keywordsKey: 'dashboard.search.entries.org_api.keywords',
    icon: Key,
    href: '/dash/org/settings/api',
    group: 'settings',
    aiSummary: 'API access: create and manage API tokens for integrations.',
    aiHints: [
      'How do I create an API token?',
      'What can the API do?',
      'How do I revoke a token?',
    ],
  },
  {
    id: 'dash.org.sso',
    titleKey: 'dashboard.organization.settings.tabs.sso',
    descriptionKey: 'dashboard.search.entries.org_sso.description',
    keywordsKey: 'dashboard.search.entries.org_sso.keywords',
    icon: Lock,
    href: '/dash/org/settings/sso',
    group: 'settings',
    aiSummary: 'Single sign-on: SAML and OIDC identity provider configuration.',
    aiHints: [
      'How do I set up SSO?',
      'Which identity providers are supported?',
      'How do I enforce SSO for users?',
    ],
  },
  {
    id: 'dash.org.usage',
    titleKey: 'dashboard.organization.settings.tabs.usage',
    descriptionKey: 'dashboard.search.entries.org_billing.description',
    keywordsKey: 'dashboard.search.entries.org_billing.keywords',
    icon: ChartBar,
    href: '/dash/org/settings/usage',
    group: 'settings',
    aiSummary: 'Usage and billing: plan usage, limits, seats and invoices.',
    aiHints: [
      'How do I check my usage?',
      'How do I upgrade my plan?',
      'How do I add instructor seats?',
      'Where do I see invoices?',
    ],
  },
  {
    id: 'dash.org.other',
    titleKey: 'dashboard.organization.settings.tabs.other',
    descriptionKey: 'dashboard.search.entries.org_other.description',
    keywordsKey: 'dashboard.search.entries.org_other.keywords',
    icon: DotsThree,
    href: '/dash/org/settings/other',
    group: 'settings',
    aiSummary: 'Other organization settings: signup, notifications and danger zone.',
    aiHints: [
      'How do I configure signup?',
      'How do I delete the organization?',
      'How do I manage notifications?',
    ],
  },
]
