import {
  CurrencyCircleDollar,
  Tag,
  UsersThree,
  Gear,
  User as UserIcon,
} from '@phosphor-icons/react'
import type { SearchMeta } from '@/lib/dashboard-search/types'

export const searchMetas: SearchMeta[] = [
  {
    id: 'dash.payments.overview',
    titleKey: 'dashboard.search.entries.payments_overview.title',
    descriptionKey: 'dashboard.search.entries.payments_overview.description',
    keywordsKey: 'dashboard.search.entries.payments_overview.keywords',
    icon: CurrencyCircleDollar,
    href: '/dash/payments/overview',
    group: 'payments',
    featureKey: 'payments',
    aiSummary: 'Payments overview: revenue, transactions and payout status across the organization.',
    aiHints: [
      'How do I see my revenue?',
      'How do I track transactions?',
      'Where do I see payouts?',
    ],
  },
  {
    id: 'dash.payments.offers',
    titleKey: 'dashboard.search.entries.payments_products.title',
    descriptionKey: 'dashboard.search.entries.payments_products.description',
    keywordsKey: 'dashboard.search.entries.payments_products.keywords',
    icon: Tag,
    href: '/dash/payments/offers',
    group: 'payments',
    featureKey: 'payments',
    aiSummary: 'Offers and products: sell courses and bundles with pricing, coupons and sales.',
    aiHints: [
      'How do I create a paid course?',
      'How do I set up a coupon?',
      'How do I create a bundle?',
    ],
  },
  {
    id: 'dash.payments.groups',
    titleKey: 'dashboard.search.entries.payments_groups.title',
    descriptionKey: 'dashboard.search.entries.payments_groups.description',
    keywordsKey: 'dashboard.search.entries.payments_groups.keywords',
    icon: UsersThree,
    href: '/dash/payments/groups',
    group: 'payments',
    featureKey: 'payments',
    aiSummary: 'Customer groups: segment buyers and assign pricing or access by group.',
    aiHints: [
      'How do I create a customer group?',
      'How do I assign a group to an offer?',
    ],
  },
  {
    id: 'dash.payments.configuration',
    titleKey: 'dashboard.search.entries.payments_configuration.title',
    descriptionKey: 'dashboard.search.entries.payments_configuration.description',
    keywordsKey: 'dashboard.search.entries.payments_configuration.keywords',
    icon: Gear,
    href: '/dash/payments/configuration',
    group: 'payments',
    featureKey: 'payments',
    aiSummary: 'Payment configuration: connect Paystack, set currencies and manage tax.',
    aiHints: [
      'How do I connect Paystack?',
      'How do I set my currency?',
      'How do I configure tax?',
    ],
  },
  {
    id: 'dash.payments.customers',
    titleKey: 'dashboard.search.entries.payments_customers.title',
    descriptionKey: 'dashboard.search.entries.payments_customers.description',
    keywordsKey: 'dashboard.search.entries.payments_customers.keywords',
    icon: UserIcon,
    href: '/dash/payments/customers',
    group: 'payments',
    featureKey: 'payments',
    aiSummary: 'Customers: everyone who has purchased, with their orders and payment history.',
    aiHints: [
      'How do I find a customer?',
      'How do I see someone\'s orders?',
      'How do I issue a refund?',
    ],
  },
]
